[package]
name = "lidar-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.16.0"
nonmax = "0.5.5"
offset-allocator = "0.1.0"
rand = "0.8.5"
bevy = { path = "../bevy" }
#bevy_xpbd_3d = "0.4.2"
